## Application Route
---

default:
  controller: Climate
  action: climate

  children:

    search:
      options:
        n:
          type: int
          default: 10
      controller: search
      action: search