## Application Route
---

default:
  controller: Climate
  action: climate
  man: Climate Application Manual Page
  
  children:

    word:
      options:
        n:
          type: int
          default: 1
          man: number of time the word has to be written
          
        w:
          type: string
          man: the word to write
          
      controller: Climate
      action: word
      man: Write a word