## Application Route
---

default:
  controller: Climat
  action: climat

  children:

    search:
      options:
        n:
          type: int
          default: 10
      controller: search
      action: search